version: "3"

services:
  flutter-app: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: eMission_app
    working_dir: /home/user/eMission
    command: flutter run
    depends_on:
      - node-server
    environment: 
      DB_HOST: "mcs.drury.edu"
      DB_PORT: 3306
      DB_USER: "emission"
      DB_PASSWORD: "Letmein!eCoders"
      DB_DATABASE: "emission"
    

  node-server:
    image: node:14
    restart: always
    working_dir: /home/user/emission/api
    command: npm start
    ports:
      - "3000:3000"
    volumes:
       - ./api:/home/user/emission/api


